plugins {
    id 'com.android.application'
}

android {
    namespace 'com.smart.suitcase.oppowatch'
    compileSdk 35

    defaultConfig {
        applicationId 'com.smart.suitcase.oppowatch'
        minSdk 26
        targetSdk 35
        versionCode 8
        versionName '2.1'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    lint {
        disable 'IconLauncherShape'
    }
}
